# executor: local
jobs: 100
local-cores: 32  # Allow 4 jobs in parallel (4 * 8 threads = 32 cores)
cores: 10
latency-wait: 5
use-envmodules: True
use-conda: False
# quiet: all
default-resources:
  - runtime=5
  - mem_mb_per_cpu=16000
  - disk_mb=2000
